### ISSUE TITLE
jena text query cache mechanism

### ISSUE THREAD

**Issue by eroux** [buda-base/lds-queries#18]
@xristy this is a tricky question for you:

I often use this pattern in the queries: I do a text search several times in different unions ([example](https://github.com/buda-base/lds-queries/blob/newbiblio/library/placeGraph.arq)). It's fast as the result gets cached the first time. I just had the idea "hey, maybe in the calls after the first one I don't need to pass the "highlight:" argument and I don't need to get the score and match... but then I wondered how the cache behave if I:
- remove the "highlight:" argument
- don't fetch the score and match (maybe the behavior is different)
in the calls after the first one.

Would you happen to know that Chris?

**Comment by xristy** [comment]
@eroux the [cache key](https://github.com/buda-base/jena/blob/146e85fd845a66c055045684011e924a4575f450/jena-text/src/main/java/org/apache/jena/query/text/TextQueryPF.java#L302) is computed via:
```
String cacheKey = subj + " " + limit + " " + match.getProps() + " " + qs + " " + lang + " " + graphURI ;
```
It doesn't depend on the score or highlight.

**Comment by eroux** [comment]
ah excellent, thanks! what's in `match.getProps()`?
