### ISSUE TITLE
cleanup

### ISSUE THREAD

**Issue by eroux** [buda-base/lds-queries#4]
I think most queries were experimental and are not used, maybe a little cleanup wouldn't harm?

**Comment by eroux** [comment]
see https://github.com/buda-base/public-digital-library/issues/41

Here's a list of queries I think we should keep:
- `library/`
   - `Ann*.arq` (et seq.: used in lds-pdi)
   - `resForMarc.arq`
   - `Resgraph.arq` (et seq.: used in pdl)
   - `Taxtree.arq`
   - `allAssocResources.arq`
   - `placeAllAssociations.arq`
   - `rootSearchGraph.arq`
   - `workFacetGraph.arq`
   - `personFacetGraph.arq`
   - `chunksFacetGraph.arq`
   - `placeAllAssociations.arq`
   - `workAllAssociations.arq`
   - `personAllAssociations.arq`
   - `topicAllAssociations.arq`
- `public/`
   - `Ann*.arq` (used in lds-pdi)
   - `IIIF*.arq` (used by IIIF servers)
   - `Resgraph.arq` (I think it's used in lds-pdi?)
   - `volumesForWork.arq`  (used by some scripts)
   - `Work_outline.arq` (might be 
 
are there other queries that need to be kept? Marc, does lds-pdi use queries other than those listed above? If not, I think the non-listed queries should be just removed (I'm not sure what the `old/` folder is for...)

**Comment by eroux** [comment]
thanks!

**Comment by berger-n** [comment]
sorry I've forgotten this one: http://purl.bdrc.io/graph/Etext_base?I_LIM=500&R_RES=bdr%3AUT1KG4884_003_0001
