### ISSUE TITLE
ChunksByPage when one of the boundaries is missing

### ISSUE THREAD

**Issue by eroux** [buda-base/lds-queries#48]
for instance

http://ldspdi.bdrc.io/lib/ChunksByPage?R_RES=bdr:UTIE0OPP000349_v001&I_START=3&I_END=12

there's no text on page 3, but there is text on pages 4, etc. so it shouldn't return nothing. Not an easy one...

**Comment by eroux** [comment]
related to https://github.com/buda-base/lds-queries/issues/10

**Comment by berger-n** [comment]
I may have a workaround for this
knowing first/last page numbers before calling the query:
![image](https://user-images.githubusercontent.com/33383857/92597553-d7ab2800-f2a7-11ea-8017-b669954e82ef.png)

**Comment by berger-n** [comment]
perfect! thanks
