### ISSUE TITLE
etextContextFacetGraph not returning matching chunks

### ISSUE THREAD

**Issue by berger-n** [buda-base/lds-queries#54]
see http://purl.bdrc.io/lib/etextContentFacetGraph?LG_NAME=bo-x-ewts&L_NAME=%22spyod%20%27jug%22
`bdr:UT3JT13379_001_0001` has matching chunks like `bdr:EC34F7DBE013DECFF2` but they are not returned by query 

(in [this query](https://purl.bdrc.io/lib/etextContentFacetGraph?LG_NAME=bo&L_NAME=%22%E0%BD%82%E0%BD%84%E0%BC%8B%E0%BD%82%E0%BD%B2%E0%BD%A6%E0%BC%8B%E0%BD%A2%E0%BE%9F%E0%BD%BA%E0%BD%93%E0%BC%8B%E0%BD%85%E0%BD%B2%E0%BD%84%E0%BC%8B%E0%BD%A0%E0%BD%96%E0%BE%B2%E0%BD%BA%E0%BD%A3%E0%BC%8B%E0%BD%94%E0%BD%A2%E0%BC%8B%E0%BD%A0%E0%BD%96%E0%BE%B1%E0%BD%B4%E0%BD%84%E0%BC%8C%E0%BC%8D%20%E0%BC%8D%E0%BD%A0%E0%BD%82%E0%BD%82%E0%BC%8B%E0%BD%94%E0%BC%8B%E0%BD%98%E0%BD%BA%E0%BD%91%E0%BC%8B%E0%BD%94%E0%BC%8B%E0%BD%A6%E0%BE%90%E0%BE%B1%E0%BD%BA%E0%BC%8B%E0%BD%98%E0%BD%BA%E0%BD%91%E0%BC%8B%E0%BD%94%22~1) all matching chunks for `bdr:UT23703_1415_0000` are returned though)

**Comment by eroux** [comment]
moved to https://github.com/buda-base/xmltoldmigration/issues/148

**Comment by eroux** [comment]
it's fixed now
