### ISSUE TITLE
Return image groups synced for a given RID

### ISSUE THREAD

**Issue by TBRC-Travis** [buda-base/lds-queries#86]
would like a LDS query for multiple volume works - for a given RID return only the image groups / volumes in the work that have been synced

**Comment by TBRC-Travis** [comment]
@eroux I'll test this out and see if it suits our needs.  thanks!

**Comment by jimk-bdrc** [comment]
Thanks, @eroux

**Comment by jimk-bdrc** [comment]
I've been using this quite successfully as part of a script named [validate-sync](https://github.com/buda-base/archive-ops/blob/72df227ff41e352ccf21a53bf1cafd8ff6ac6555/scripts/transfer/validate-sync). I'm happy to call this complete. WDYT?
