### ISSUE TITLE
query to generate IGRID metadata from BUDA for IA

### ISSUE THREAD

**Issue by TBRC-TimB** [buda-base/lds-queries#88]
The last bit of metadata we still generate from tbrc.org for the IA process is the image group level metadata. 
we need one file for each Volume in a Work. Usually we generate these by looping through the IGRIDs and making individual calls to tbrc.org. 

Sample data: Typically the files are .xml but github blocks that file format. 
[I1KG21234.txt](https://github.com/buda-base/lds-queries/files/8613035/I1KG21234.txt)
[I1KG21234.zip](https://github.com/buda-base/lds-queries/files/8613048/I1KG21234.zip)

**Comment by eroux** [comment]
Here's a query you can use for the script : https://ldspdi.bdrc.io/query/table/AO_IGinfoInW?R_RES=bdr:W1PD96684

it lists the volume IDs, volume number, number of tbrc intro pages (which should in theory be used in the php to determine the thumbnail) and the total number of pages (which will be < 3 for an unsynced volume). The list is ordered by volume number.

One potential benefit is that IIRC the IA script just takes the xml order of the image groups as their actual order, which isn't always true (see [this example](https://legacy.tbrc.org/xmldoc?rid=W1PD96684) with volume 62 at the end), while this query sorts by volume number

That will probably require some adaptations to the script, but BUDA doesn't support tbrc.org xml files

**Comment by eroux** [comment]
note that the image list is not in the database so you'll have to get it from the `dimensions.json` file (or through the API call). In the future we also might want to consider listing images with their corrected order and pagination from the bvm, that would add some value over our current upload... but it's a little more complex, we can keep it for later
